import React from "react";
import { Container, Row, Col } from "react-bootstrap";
import ProjectCard from "./ProjectCards";
import Particle from "../Particle";
import ecommerce from "../../Assets/Projects/ecommerce.png";
import chatbot from "../../Assets/Projects/chatbot.png";
import iims from "../../Assets/Projects/iims.png";
import bank from "../../Assets/Projects/bank.png";
import nlp from "../../Assets/Projects/nlp.png";

function Projects() {
  return (
    <Container fluid className="project-section">
      <Particle />
      <Container>
        <h1 className="project-heading">
          My Recent <strong className="purple">Works </strong>
        </h1>
        <p style={{ color: "white" }}>
          Here are a few projects I've worked on recently.
        </p>
        <Row style={{ justifyContent: "center", paddingBottom: "10px" }}>
          <Col md={4} className="project-card">
            <ProjectCard
              imgPath={iims}
              isBlog={false}
              title="IIMS Web Application for Incident Analysis & Emergency Response"
              description="In collaboration with Professor Chunming Qiao, I contributed to the successful development of an IIMS 
              web application utilizing ReactJs for frontend, Python Flask for backend, and PostgreSql for data management. 
              The application's core functionality revolved around analyzing Wejo data to generate insightful maps of vehicle 
              behavior during incidents. This, in turn, supported informed decision-making for dispatching emergency services and 
              optimizing traffic flow. Through this project, we aimed to significantly enhance incident response strategies and 
              contribute to the broader domain of emergency management."
              ghLink="https://github.com/djain1309/iims_front"
              demoLink="https://github.com/djain1309/iims_backend"
            />
          </Col>

          <Col md={4} className="project-card">
            <ProjectCard
              imgPath={nlp}
              isBlog={false}
              title="Authorship Attribution for Neural Text Generation (Synthetically generated text detection)[Group Project]"
              description="Advancements in neural language modeling have made it challenging to differentiate between human and 
              machine-generated texts. However, distinguishing between the two has become crucial for tasks like Authorship Attribution, where identifying the origin of a text is essential. So in our implementation, we have 3 problems:

              *Determine if texts T1 and T2 are generated by the same NLG method or human.
              *Differentiate between a text T1 written by a human or generated by any of k NLG methods.
              *Attribute the text T1 to a specific NLG method among k alternatives."
              ghLink="https://github.com/jasukaur/authorship-attribution"
            />
          </Col>

          <Col md={4} className="project-card">
            <ProjectCard
              imgPath={chatbot}
              isBlog={false}
              title="Chat Bot"
              description="Developed Multi-topic Information Retrieval Chatbot capable of resolving 80% of user queries and maintaining a
              natural conversation flow.
              Designed UI using ReactJs, allowing users to ask queries to the bot and able to coherently converse for 4 turns"
              ghLink="https://github.com/djain1309/RedditChatBot_NLP/tree/master"
            />
          </Col>

          <Col md={4} className="project-card">
            <ProjectCard
              imgPath={ecommerce}
              isBlog={false}
              title="Ecommerce - Agriculture Based Website"
              description="Through the execution of this project, we harnessed the power of micro-frontends to optimize our ecommerce platform's development process. 
              By creating modular NPM modules, implementing CI/CD practices, and prioritizing version control, we not only streamlined the current project 
              but also paved the way for accelerated and efficient development in subsequent ventures. 
              This strategic approach positions our team for continued success in the ever-evolving landscape of ecommerce technology."
            />
          </Col>

          <Col md={4} className="project-card">
            <ProjectCard
              imgPath={bank}
              isBlog={false}
              title="Credit Card - Prediction [Team Project]"
              description="Credit score cards are a common risk control method in the financial industry. 
              It uses personal information and data submitted by credit card applicants to predict the probability of future defaults and credit card borrowings. The bank is able to decide whether to issue a credit card to the applicant. 
              Credit scores can objectively quantify the magnitude of risk.
              At present, with the development of machine learning algorithms. More predictive methods such as Boosting, Random Forest, and Support Vector Machines have been introduced into credit card scoring. However, these methods often do not have good transparency. 
              It may be difficult to provide customers and regulators with a reason for rejection or acceptance."
              ghLink="https://github.com/djain1309/Bank-loan-prediction"
            />
          </Col>
        </Row>
      </Container>
    </Container>
  );
}

export default Projects;
